In [1]:
#create an array
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created :\n",a)

Array created :
 [[1 2 4]
 [5 8 7]]


In [2]:
#creating a 3*4 array with all zeros
b=np.zeros((3,4))
print("Array with nall zeros :\n",b)

Array with nall zeros :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [4]:
#create an array with random value
d=np.random.random((2,2))
print("Random array:\n",d)

Random array:
 [[0.91981433 0.58531628]
 [0.1633917  0.89480793]]


In [8]:
#creating a sequence of integers from 0 to 30 with step of 5
import numpy as np
e=np.arange(0,30,5)
print(e)


[ 0  5 10 15 20 25]


In [18]:
#Reshaping 3*4 array to 2*2*3 array
import numpy as np
arr=np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr=arr.reshape(4,3)
print("\n Original array:\n",arr)
print("Reshaped array[4,3]:\n",newarr)





 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [19]:
#flatten array
flarr=arr.flatten()
print("\n Original array:\n",arr)
print("\n flattened array:\n",flarr)


 Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 flattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]
